name: RELEASE

on:
  release:
    types:
      - created
      - edited

jobs:
  prepare_version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: m3ntorship/m3ntorship.com
        ref: develop
    - run: |
        ls -al
        git rev-parse --short=4 HEAD
        echo ::set-env name=M3_VERSION::$(git rev-parse --short=4 HEAD)
        echo $M3_VERSION is that
  
  deploy_dev:
    needs: [prepare_version]
    runs-on: ubuntu-latest

    steps:
    - name: Runs if it is prerelease
      run: |
        echo $M3_VERSION
        echo "${{toJson(github.event)}}"
        echo ${{github.event.release.tag_name}}