name: RELEASE

on:
  release:
    types:
      - created
      - edited

jobs:
  
  prepare:
    runs-on: ubuntu-latest
    
    outputs:
      sha: ${{ steps.prepare.outputs.sha }}
      version: ${{ steps.prepare.outputs.version }}
      image_frontend: m3ntorshipci/m3ntorshipcom-frontend
      dockerfile_frontend: Dockerfile.playground.frontend
    steps:
    - uses: actions/checkout@v2
      with:
        repository: m3ntorship/m3ntorship.com
        ref: develop
    - id: prepare
      run: |
        echo "::set-output name=sha::$(git rev-parse HEAD)"
        echo "::set-output name=version::$(git rev-parse --short=4 HEAD)"
  
  build_frontend:
    needs: [prepare]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: m3ntorship/m3ntorship.com
        ref: ${{needs.prepare.outputs.sha}}

    - name: install dependencies
      env:
        M3NTORSHIP_APP_STRAPI_URL: http://localhost:1337
      run: |
        yarn --cwd frontend 
        yarn --cwd frontend build
      # docker build -t m3ntorshipci/m3ntorshipcom-frontend:0.6 -f Dockerfile.playground.frontend .
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{needs.prepare.outputs.image_frontend}}
        dockerfile: ${{needs.prepare.outputs.dockerfile_frontend}}
        tags: ${{needs.prepare.outputs.version}}
