name: RELEASE

on: 
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: nile

    - name: Run a multi-line script
      run: |
        echo ${{github.event.release.tag_name}}